// Contains the name of the sidebar menu items and the corresponding role access
export const AccessRules: { [key: string]: string[] } = {
  // Admin
  Users: ['MANAGE USERS'],
  Roles: ['MANAGE ROLE'],
  'Account Officers': ['MANAGE ACCOUNT OFFICER'],
  'Posting Limits': ['MANAGE POSTING LIMIT'],
  'GL Accounts': ['MANAGE GL ACCOUNT'],
  Officers: ['OFFICER TRANSFER'],
  Directors: ['CREATE DIRECTORS', 'CREATE DIRECTORS MANDATE'],
  Groups: ['MANAGE GROUPS', 'MANAGE GROUP MEMBERS'],
  // Customer Service
  Customer: [
    'CUSTOMER INFO',
    'CUSTOMER CREATION',
    'EDIT CUSTOMER',
    'ACCOUNT CREATION',
    'EDIT ACCOUNT',
    'MANAGE MANDATE',
    'MANAGE LIEN',
    'CHECQUEBOOK  EDIT',
    'ACCOUNT REACTIVATION',
    'RANGE CHEQUE',
    'CLOSE ACCOUNT',
    'MOVE CASA ACCOUNT'
  ],
  'General Ledgers': ['MANAGE GL ACCOUNT'],
  Accounts: [
    'ACCOUNT CREATION',
    'EDIT ACCOUNT',
    'MANAGE MANDATE',
    'MANAGE LIEN',
    'CHECQUEBOOK  EDIT',
    'ACCOUNT REACTIVATION',
    'RANGE CHEQUE',
    'CLOSE ACCOUNT',
    'MOVE CASA ACCOUNT'
  ],
  // Requests
  Requests: ['AUTHORISE'],
  // Setup
  Company: [
    'SETUP COMPANY',
    'MANAGE BRANCH',
    'MANAGE COUNTRY',
    'MANAGE TOWN',
    'MANAGE REGIONS',
    'MANAGE HOLIDAYS',
    'STATE MANAGEMENT',
    'MANAGE DEPARTMENTS'
  ],
  'Product and GL': [
    'LOAN PRODUCT SETUP',
    'PRODUCT DOC.',
    'TREASURY PRODUCT SETUP',
    'MANAGE GL NODE',
    'MANAGE GL CLASS',
    'MANAGE EXCEPTION',
    'SETUP CONDITION PRECEDENT',
    'MANAGE INTEREST',
    'MANAGE CHARGES'
  ],
  'Operations Setup': [
    'COMMERCIAL BANKS',
    'CHEQUE BOOKS',
    'CLEARING BANKS',
    'DORMANCY CRITERIA'
  ],
  KYC: [
    'MANAGE TOWN',
    'MANAGE EDUCATION',
    'MANAGE GROUP',
    'MANAGE PROFESSION',
    'ZONE SETUP',
    'RELATIONSHIP',
    'MANAGE INDUSTRY',
    'MANAGE DOCUMENT'
  ],
  Cash: [
    'BATCH POSTING',
    'BULK UPLOAD',
    'CASH DEPOSIT',
    'CASH WITHDRAWAL',
    'CHARGE CONCESSION',
    'CASH JOURNALS'
  ],
  Transfer: ['BATCH POSTING', 'BULK UPLOAD', 'NIP TRANSFER', 'TRANSFER'],
  Cheque: [
    'RETURN CHEQUE REVERSAL',
    'CHEQUE DEPOSIT',
    'CHEQUE WITHDRAWAL',
    'CLEARING'
  ],
  'Vault Management': ['VAULT MANAGEMENT'],
  // Loans
  'Loan Directory': [
    'LOAN UNDERWRITING',
    'VIEW LOAN APPLICATION',
    'LOAN UNDERWRITING REVIEW',
    'LOAN RESTRUCTURE',
    'PARTIAL PAYOFF',
    'CANCEL LOAN',
    'VIEW LOAN',
    'LOAN STATUS',
    'CLOSE MATURED LOAN ACCOUNT',
    'LOAN CLOSURE_WRITEOFF',
    'GROUP LOAN UNDERWRITING',
    'GROUP LOAN UNDERWRITING REVIEW',
    'GROUP LOAN DISBURSE',
    'CREATE GUARANTOR',
    'EDIT GUARANTOR',
    'GUARANTOR S MANDATE',
    'LOAN OFFER LETTER'
  ],
  Overdrafts:['OVERDRAFT'],
  // Reports
  Overview: ['allow', 'allow'],
  'Custom Report': [
    'DAILY JOURNAL',
    'ACCOUNT DETAILS',
    'CHEQUE BOOK STATUS',
    'POSTING JOURNAL',
    'STATEMENTS',
    'GROUP REPORT',
    'TELLER POSTINGS SUMMARY',
    'CUSTOMER BALANCES',
    'HOLDT TRANS',
    'STANDING INSTRUNCTIONS',
    'DORMANT ACCOUNTS',
    'TRANSACTIONS IN CLEARING',
    'PRODUCT SUMMARY',
    'TRIAL BALANCE BY DATE',
    'TD MATURITY REPORT',
    'DRILL DOWN GL REPORT',
    'PLAIN TRIAL BALANCE',
    'PROFIT OR LOSS',
    'BALANCE SHEET',
    'LOAN OVERDUE',
    'Maturity Loan Report',
    'Weekly Loan Repayment Report',
    'NFIU Report',
    'Loan Account Officer',
    'CHART OF ACCOUNTS',
    'New Risk Report',
    'DISBURSED LOANS REPORT',
    'GROUP LOAN REPORT',
    'Group Membership Report',
    'PORTFOLIO AT RISK',
    'Officer CABAL summary',
    'INCOME ASSURANCE',
    'TELLER BALANCE REPORT',
    'INFLOW AND OUTFLOW REPORT',
    'Accounts In Debit report',
    'INVESTMENT ADVICE',
    'ICAD REPORT',
    'SCV REPORT',
    'Takings Report',
    'Placements Reports'
  ],
  'Audit Trail': ['AUDIT TRAIL REPORT']
};
