env:
  browser: true
  es2021: true
  jest: true
extends:
  - next/core-web-vitals
  - plugin:testing-library/react
  - plugin:react/recommended
  - airbnb
  - plugin:css/recommended
  - plugin:react-hooks/recommended
  - prettier
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 14
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - css
  - prettier
rules:
  {
    'jsx-a11y/anchor-is-valid':
      [
        'warn',
        {
          'components': ['Link'],
          'specialLink': ['hrefLeft', 'hrefRight'],
          'aspects': ['noHref', 'invalidHref', 'preferButton'],
        },
      ],
    'react/forbid-prop-types': ['warn', { 'forbid': ['any'] }],
    'jsx-a11y/label-has-associated-control':
      [
        0,
        {
          'labelComponents': ['FormLabel'],
          'labelAttributes': ['label'],
          'controlComponents': ['input'],
          'depth': 1,
        },
      ],
    'no-restricted-syntax':
      ['warn', 'WithStatement', "BinaryExpression[operator='in']"],
    'indent': 'off',
    'quotes': ['warn', 'single'],
    'semi': ['warn', 'always'],
    'comma-dangle': ['off', 'never'],
    'react/prop-types':
      [0, { ignore: [], customValidators: [], skipUndeclared: [] }],
    'react/state-in-constructor': [warn, 'always'],
    'import/order':
      ['warn', { 'pathGroups': [{ 'pattern': '~/**', 'group': 'external' }] }],
    'spaced-comment': ['warn', 'always', { 'exceptions': ['-', '+'] }],
    'react/destructuring-assignment': [warn, 'always'],
    'react-hooks/rules-of-hooks': 1,
    'react-hooks/exhaustive-deps': 1,
    'react/jsx-filename-extension': [1, { 'extensions': ['.jsx', '.tsx'] }],
    'import/extensions': ['warn', { 'json': never' }],
    'import/prefer-default-export': 'off',
    'lines-around-directive': 'off',
    'react/no-array-index-key': 'off',
    'no-unused-vars': 'warn',
    "@typescript-eslint/no-unused-vars": 'warn',  
    'react/require-default-props': 'off',
    'react/function-component-definition': 'off',
    'react/react-in-jsx-scope': 'off',
    'consistent-return': 'off',
    'arrow-body-style': 'off',
    'react/jsx-props-no-spreading': 'off',
    'react/no-unstable-nested-components': 'off',
  }
