interface IQueryKeys {
  user: string;
  branches: string;
  accountOfficer: string;
  getAccountOfficerByCode: string;
  getAllCustomerAccountProducts: string;
  getCustomerAccountInfo: string;
  roleByID: string;
  getUserByID: string;
  getSupervisorByID: string;
  searchUsers: string;
  department: string;
  glAccount: string;
  glCurrency: string;
  glType: string;
  role: string;
  searchCustomer: string;
  searchStaff: string;
  getDocuments: string;
  getCustomerById: string;
  getMandateDetailsByAccountNumber: string;
  getAllGroups: string;
  getAllIdTypes: string;
  getAllTitles: string;
  getAllCountries: string;
  getAllStates: string;
  getAllTown: string;
  getAllRelationships: string;
  getProductDetailsByPcode: string;
  dataCapture: string;
  authPriviledge: string;
  status: string;
  node: string;
  glClasses: string;
  getPostinglimitByCode: string;
  getAssignedDataCaptureByRoleID: string;
  getAssignedAuthPriviledgesByRoleID: string;
  searchUserByRoleID: string;
  postingLimit: string;
  getGLAccountByGlNumber: string;
  getPostingLimitByBranchCodeAndRoleid: string;
  state: string;
  setupCompany: string;
  getBranches: string;
  getBranchTypes: string;
  getCity: string;
  getAllEducation: string;
  getAllSectors: string;
  getAllOccupation: string;
  getBranchByCode: string;
  getAllBranch: string;
  getCountryByName: string;
  getTownByName: string;
  getRegionById: string;
  getHolidayById: string;
  getStateById: string;
  getProductType: string;
  getGlClassCode: string;
  getExceptionByCode: string;
  getSetupCondition: string;
  getInterest: string;
  getAllLien: string;
  getAllLienReason: string;
  getLienDetail: string;
  getAllChequesBooks: string;
  getCustomerAccountInfoList: string;
  getChequeInfo: string;
  filterCustomerSearch: string;
  filterUserSearch: string;
  filterAccountOfficerSearch: string;
  filterRoleSearch: string;
  filterBranchSearch: string;
  filterCountrySearch: string;
  filterTownSearch: string;
  filterGroupSearch: string;
  filterRegionSearch: string;
  filterHolidaySearch: string;
  getDepartmentById: string;
  getGlNodeById: string;
  filterCustomerAccountSearch: string;
  getGroupMembersbyGroupId: string;
  getGroupById: string;
  getCommercialBankByCode: string;
  filterDirectorsSearch: string;
  getIndustryByCode: string;
  filterIndustrySearch: string;
  getProfessionByCode: string;
  filterProfessionSearch: string;
  getClearingBankByCode: string;
  getCommercialBank: string;
  getDormancyByCode: string;
  getChequeBookById: string;
  getTransactionTypeByCode: string;
  filterTransactionSearch: string;
  filterClearingBankSearch: string;
  filterDormancySearch: string;
  filterCommercialBankSearch: string;
  filterChequeSearch: string;
  getSectorByCode: string;
  filterSectorSearch: string;
  filterGroupIdSearch: string;
  getGroupByID: string;
  filterGlNodeSearch: string;
  filterGlClassSearch: string;
  filterInterestSearch: string;
  getDirectorMandateDetails: string;
  getZoneById: string;
  filterZoneSearch: string;
  getRelationshipById: string;
  filterRelationshipSearch: string;
  filterPostingLimitSearch: string;
  filterGLAccountSearch: string;
  getTransactionType: string;
  getGenerateBatchNo: string;
  createCharge: string;
  filterStateSearch: string;
  filterDepartmantSearch: string;
  getChargeConcession: string;
  getZones: string;
  getClearingBank: string;
  getGlNodeByTypeCode: string;
  getGlClassByNodeCode: string;
  getGlDetails: string;
  getBranchCode: string;
  getCountryByCode: string;
  getTownByCode: string;
  getRegion: string;
  getNipBeneficiaryDetails: string;
  filterUserByRoleSearch: string;
  glDetailsByBranchCode: string;
  getGLAllAccount: string;
  filterGeneralLedgerSearch: string;
  getGlDetailbyCodeAnduserId: string;
  getAllLoansProduct: string;
  getLoansProductDetailCode: string;
  getAllLoansPurpose: string;
  getAllLoansources: string;
  getAllLoanCollaterals: string;
  filterExceptionSearch: string;
  filterSetupConditionSearch: string;
  getChargeByCode: string;
  filterChargeSearch: string;
  getCompanyById: string;
  getAllCompany: string;
  getLoanProductByCode: string;
  filterLoanAccountSearch: string;
  getDemandDepositByCode: string;
  getAllLoans: string;
  getAuditTrails: string;
  fetchAllUserRequest: string;
  fetchPendingRequest: string;
  fetchRejectedRequest: string;
  accountEnquiry: string;
  chequeBook: string;
  customerBalance: string;
  getAllProductByCode: string;
  plainTrialBalance: string;
  getTermDeporitMaturityReport: string;
  chartAccount: string;
  portfolioAtRisk: string;
  detailedpPortfolioAtRisk: string;
  glMainGroupReport: string;
  glSubGroupReport: string;
  getMinMaxCreditInterest: string;
  getLoanClass: string;
  getInterestRate: string;
  overloanDueReport: string;
  tellerBalance: string;
  getTellerBalanceByUserTellerNumber: string;
  getProductClass: string;
  getAllProduct: string;
  getAllException: string;
  getAllNibbsBank: string;
  getLoanTerm: string;
  resetPassword: string;
  getGlType: string;
  destinationAccount: string;
  getCustomerByIdCodes: string;
  getSystemDate: string;
  getCounterCheqNo: string;
  getAccountDetails: string;
  getAllLoanRepaymentTypes: string;
  getDirectorsByCustomerId: string;
  getDirectorById: string;
  getStateByCountryCode: string;
  getTownByStateCode: string;
  getCustomerAccountsByOfficerCode: string;
  getRoleByID: string;
  filterFinanceAccount: string;
  getAllOverdraft: string;
  getNextApplicationNo: string;
  glDetail: string;
  termDeporitMaturityReport: string;
  getStatementId: string;
  filterStatementSearch: string;
  filterDocumentSearch: string;
  getDocumentById: string;
  viewAuthDetailsGeneral: string;
  filterEducationSearch: string;
  getEducationByCode: string;
  beneficiaryCustomer: string;
  getOverdraftDetail: string;
  bankLogo: string;
  inflowOutflowReport: string;
  getGroupLoan: string;
  getStandingInstruction: string;
  getAllTermDepositMaturityReports: string;
  getincomeAssurance: string;
  geTransactionClearing: string;
  getAccountInDebit: string;
  getTellerBalanceReport: string;
  getAllProductDocs: string;
  generateProductCode: string;
  getTrialBalanceByGroup: string;
  dormantAccount: string;
  maturityLoan: string;
  statementOfAccount: string;
  balanceSheet: string;
  balanceSheetbyId: string;
}

export const queryKeys: IQueryKeys = {
  getAllTermDepositMaturityReports: 'getAllTermDepositMaturityReports',
  getTrialBalanceByGroup: 'getTrialBalanceByGroup',
  getAllProductDocs: 'getAllTermDepositMaturityReports',
  getTellerBalanceReport: 'getTellerBalanceReport',
  getAccountInDebit: 'getAccountInDebit',
  filterEducationSearch: 'filterEducationSearch',
  inflowOutflowReport: 'inflowOutflowReport',
  viewAuthDetailsGeneral: 'viewAuthDetailsGeneral',
  getEducationByCode: 'getEducationByCode',
  getDocumentById: 'getDocumentById',
  getStatementId: 'getStatementId',
  filterDocumentSearch: 'filterDocumentSearch',
  filterStatementSearch: 'filterStatementSearch',
  termDeporitMaturityReport: 'termDeporitMaturityReport',
  getNextApplicationNo: 'getNextApplicationNo',
  filterFinanceAccount: 'filterFinanceAccount',
  glDetail: 'glDetail',
  getAllOverdraft: 'getAllOverdraft',
  getCustomerAccountsByOfficerCode: 'getCustomerAccountsByOfficerCode',
  getRoleByID: 'getCustomerAccountsByOfficerCode',
  getTownByStateCode: 'getStateByCountryCode',
  getStateByCountryCode: 'getStateByCountryCode',
  getDirectorById: 'getDirectorById',
  getDirectorsByCustomerId: 'getDirectorsByCustomerId',
  getAccountDetails: 'getAccountDetails',
  getCustomerByIdCodes: 'getCustomerByIdCodes',
  detailedpPortfolioAtRisk: 'detailedpPortfolioAtRisk',
  resetPassword: 'resetPassword',
  overloanDueReport: 'overloanDueReport',
  getAllNibbsBank: 'getAllNibbsBank',
  user: 'user',
  glMainGroupReport: 'glMainGroupReport',
  glSubGroupReport: 'glSubGroupReport',
  accountEnquiry: 'accountEnquiry',
  getTermDeporitMaturityReport: 'getTermDeporitMaturityReport',
  portfolioAtRisk: 'portfolioAtRisk',
  fetchAllUserRequest: 'fetchAllUserRequest',
  fetchRejectedRequest: 'fetchRejectedRequest',
  fetchPendingRequest: 'fetchPendingRequest',
  filterUserByRoleSearch: 'filterUserByRoleSearch',
  getNipBeneficiaryDetails: 'getNipBeneficiaryDetails',
  getLienDetail: 'getLienDetail',
  getGlNodeByTypeCode: 'getGlNodeByTypeCode',
  getGlClassByNodeCode: 'getGlClassByNodeCode',
  getGlDetails: 'getGlDetails',
  getGroupById: 'getGroupById',
  getGroupMembersbyGroupId: 'getGroupMembersbyGroupId',
  getDirectorMandateDetails: 'getDirectorMandateDetails',
  filterPostingLimitSearch: 'filterPostingLimitSearch',
  filterGLAccountSearch: 'filterGLAccountSearch',
  filterGroupSearch: 'filterGroupSearch',
  filterRoleSearch: 'filterRoleSearch',
  filterAccountOfficerSearch: 'filterAccountOfficerSearch',
  filterUserSearch: 'filterUserSearch',
  filterCustomerSearch: 'filterCustomerSearch',
  filterCustomerAccountSearch: 'filterCustomerAccountSearch',
  filterDirectorsSearch: 'filterDirectorsSearch',
  getChequeInfo: 'getChequeInfo',
  getCustomerAccountInfoList: 'getCustomerAccountInfoList',
  getAllChequesBooks: 'getAllChequesBooks',
  getAllOccupation: 'getAllOccupation',
  getAllLien: 'getAllLien',
  getAllLienReason: 'getAllLienReason',
  getAllEducation: 'getAllEducation',
  getAllSectors: 'getAllSectors',
  getMandateDetailsByAccountNumber: 'getMandateDetailsByAccountNumber',
  branches: 'branches',
  accountOfficer: 'accountOfficer',
  getAccountOfficerByCode: 'getAccountOfficerByCode',
  getAllCustomerAccountProducts: 'getAllCustomerAccountProducts',
  getCustomerAccountInfo: 'getCustomerAccountInfo',
  roleByID: 'roleByID',
  getUserByID: 'getUserByID',
  getSupervisorByID: 'getSupervisorByID',
  searchUsers: 'searchUsers',
  department: 'department',
  glAccount: 'glAccount',
  getCustomerById: 'getCustomerById',
  getAllGroups: 'getAllGroups',
  getProductDetailsByPcode: 'getProductDetailsByPcode',
  glCurrency: 'glCurrency',
  glType: 'glType',
  role: 'role',
  searchCustomer: 'searchCustomer',
  searchStaff: 'searchStaff',
  getDocuments: 'getDocuments',
  getAllIdTypes: 'getAllIdTypes',
  getAllCountries: 'getAllCountries',
  getAllStates: 'getAllStates',
  getAllTitles: 'getAllTitles',
  getAllTown: 'getAllTown',
  getAllRelationships: 'getAllRelationships',
  dataCapture: 'dataCapture',
  authPriviledge: 'authPriviledge',
  status: 'status',
  node: 'node',
  glClasses: 'glClasses',
  getPostinglimitByCode: 'getPostinglimitByCode',
  getAssignedDataCaptureByRoleID: 'getAssignedDataCaptureByRoleID',
  getAssignedAuthPriviledgesByRoleID: 'getAssignedAuthPriviledgesByRoleID',
  searchUserByRoleID: 'searchUserByRoleID',
  postingLimit: 'postingLimit',
  getGLAccountByGlNumber: 'getGLAccountByGlNumber',
  getPostingLimitByBranchCodeAndRoleid: 'getPostingLimitByBranchCodeAndRoleid',
  state: 'getState',
  setupCompany: 'setupCompany',
  getBranches: 'getBranches',
  getBranchTypes: 'getBranchTypes',
  getCity: 'getCity',
  getBranchByCode: 'getBranchByCode',
  getAllBranch: 'getAllBranch',
  getCountryByName: 'getCountryByName',
  getTownByName: 'getTownByName',
  getRegionById: 'getRegionById',
  getHolidayById: 'getHolidayById',
  getStateById: 'getStateById',
  getProductType: 'getProductType',
  getGlClassCode: 'getGlClassCode',
  getExceptionByCode: 'getExceptionByCode',
  getSetupCondition: 'getSetupCondition',
  getInterest: 'getInterest',
  filterBranchSearch: 'filterBranchSearch',
  filterCountrySearch: 'filterCountrySearch',
  filterTownSearch: 'filterTownSearch',
  filterRegionSearch: 'filterRegionSearch',
  filterHolidaySearch: 'filterHolidaySearch',
  getDepartmentById: 'getDepartmentById',
  getGlNodeById: 'getGlNodeById',
  getCommercialBankByCode: 'getCommercialBankByCode',
  getIndustryByCode: 'getIndustryByCode',
  filterIndustrySearch: 'filterIndustrySearch',
  getProfessionByCode: 'getProfessionByCode',
  filterProfessionSearch: 'filterProfessionSearch',
  getClearingBankByCode: 'getClearingBankByCode',
  getCommercialBank: 'getCommercialBank',
  getDormancyByCode: 'getDormancyByCode',
  getChequeBookById: 'getChequeBookById',
  getTransactionTypeByCode: 'getTransactionTypeByCode',
  filterTransactionSearch: 'filterTransactionSearch',
  filterClearingBankSearch: 'filterClearingBankSearch',
  filterDormancySearch: 'filterDormancySearch',
  filterCommercialBankSearch: 'filterCommercialBankSearch',
  filterChequeSearch: 'filterChequeSearch',
  getSectorByCode: 'getSectorByCode',
  filterSectorSearch: 'filterSectorSearch',
  filterGroupIdSearch: 'filterGroupIdSearch',
  getGroupByID: 'getGroupByID',
  filterGlNodeSearch: 'filterGlNodeSearch',
  filterGlClassSearch: 'filterGlClassSearch',
  filterInterestSearch: 'filterInterestSearch',
  getZoneById: 'getZoneById',
  filterZoneSearch: 'filterZoneSearch',
  getRelationshipById: 'getRelationshipById',
  filterRelationshipSearch: 'filterRelationshipSearch',
  getTransactionType: ' getTransactionType',
  getGenerateBatchNo: 'getGenerateBatchNo',
  createCharge: 'createCharge',
  filterStateSearch: 'filterStateSearch',
  filterDepartmantSearch: 'filterDepartmantSearch',
  getChargeConcession: 'getChargeConcession',
  getZones: 'getZones',
  getClearingBank: 'getClearingBank',
  getBranchCode: 'getBranchCode',
  getCountryByCode: 'getCountryByCode',
  getTownByCode: 'getTownByCode',
  getRegion: 'getRegion',
  glDetailsByBranchCode: 'glDetailsByBranchCode',
  getGLAllAccount: 'getGLAllAccount',
  filterGeneralLedgerSearch: 'filterGeneralLedgerSearch',
  getGlDetailbyCodeAnduserId: 'getGlDetailbyCodeAnduserId',
  getAllLoansProduct: 'getAllLoansProduct',
  getLoansProductDetailCode: 'getLoansProductDetailCode',
  getAllLoansPurpose: 'getAllLoansPurpose',
  getAllLoansources: 'getAllLoansources',
  getAllLoanCollaterals: 'getAllLoanCollaterals',
  filterExceptionSearch: 'filterExceptionSearch',
  filterSetupConditionSearch: 'filterSetupConditionSearch',
  getChargeByCode: 'getChargeByCode',
  filterChargeSearch: 'filterChargeSearch',
  getCompanyById: 'getCompanyById',
  getAllCompany: 'getAllCompany',
  getAllLoanRepaymentTypes: 'getAllLoanRepaymentTypes',
  getAllLoans: 'getAllLoans',
  getLoanProductByCode: 'getLoanProductByCode',
  filterLoanAccountSearch: 'filterLoanAccountSearch',
  getDemandDepositByCode: 'getDemandDepositByCode',
  chequeBook: 'chequeBook',
  customerBalance: 'customerBalance',
  getAuditTrails: 'getAuditTrails',
  plainTrialBalance: 'plainTrialBalance',
  getAllProductByCode: 'getAllProductByCode',
  chartAccount: 'chartAccount',
  getMinMaxCreditInterest: 'getMinMaxCreditInterest',
  getLoanClass: 'getLoanClass',
  getInterestRate: 'getInterestRate',
  tellerBalance: 'tellerBalance',
  getTellerBalanceByUserTellerNumber: 'getTellerBalanceByUserTellerNumber',
  getProductClass: 'getProductClass',
  getAllProduct: 'getAllProduct',
  getAllException: 'getAllException',
  getLoanTerm: 'getLoanTerm',
  getGlType: 'getGlType',
  destinationAccount: 'destinationAccount',
  getSystemDate: 'getSystemDate',
  getCounterCheqNo: 'getCounterCheqNo',
  beneficiaryCustomer: 'beneficiaryCustomer',
  getOverdraftDetail: 'getOverdraftDetail',
  bankLogo: 'bankLogo',
  getGroupLoan: ' getGroupLoan',
  getStandingInstruction: 'getStandingInstruction',
  getincomeAssurance: 'getincomeAssurance',
  geTransactionClearing: 'geTransactionClearing',
  generateProductCode: 'generateProductCode',
  dormantAccount: 'dormantAccount',
  maturityLoan: 'maturityLoan',
  statementOfAccount: 'statementOfAccount',
  balanceSheet: 'balanceSheet',
  balanceSheetbyId: 'balanceSheetbyId',

};
